/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package markgen;

import markgen.html.HtmlGenerator;
import markgen.parser.MarkParser;
import markgen.command.SSG;

import picocli.CommandLine;

import java.io.IOException;
import java.io.InputStreamReader;

public class Main {
    public static void main(String[] args) {
        try {
            String[] arguments = {"ssg","-h"};
            String[] arguments2 = {"ssg", "build", "test.html", "test2.html"};
            String[] arguments3 = {"ssg", "build", "test.html", "test2.html", "--output-dir", "my_output_dir"};
            int exitCode = new CommandLine(new SSG()).execute(arguments3); 
            System.exit(exitCode);
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
}
