/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package markgen;

import markgen.parser.MarkParser;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;

public class Main {
    public static void main(String[] args){
        MarkParser p = new MarkParser();
        try {
            InputStreamReader reader = p.readFile("test.md");
            String output = p.mdToHtml(reader);
            System.out.println(output);
        }catch(IOException e ){
            e.printStackTrace();
        }
    }
}
